modLoader="javafml"
loaderVersion="[40,)"
license="GPL-3.0 license"
issueTrackerURL="https://github.com/moltenwolfcub/crafted_cuisine/issues"
showAsResourcePack=false

[[mods]]
modId="crafted_cuisine"
version="1.19-1.0.1"
displayName="Crafted Cuisine"
displayURL="https://github.com/moltenwolfcub/crafted_cuisine"
issueTrackerURL="https://github.com/moltenwolfcub/crafted_cuisine/issues"
updateJSONURL="https://raw.githubusercontent.com/moltenwolfcub/crafted_cuisine/master/update.json"
logoFile="crafted_cuisine.png"
authors="MoltenWolfCub"
description='''
A Minecraft Food Mod
'''


[[dependencies.crafted_cuisine]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.crafted_cuisine]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.19.1)"
    ordering="NONE"
    side="BOTH"

#[[dependencies.crafted_cuisine]]
#    modId="geckolib3"
#    mandatory=true
#    versionRange="[3.0.27,)"
#    ordering="NONE"
#    side="BOTH"

[[dependencies.crafted_cuisine]]
    modId="jei"
    mandatory=false
    versionRange="[9.7.0.194,)"
    ordering="NONE"
    side="CLIENT"
