modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"
issueTrackerURL="https://github.com/moltenwolfcub/cooks_kitchen/issues"
showAsResourcePack=false

[[mods]]
modId="cooks_kitchen"
version="1.18.2-0.0.1"
displayName="Cook's Kitchen"
displayURL="https://github.com/moltenwolfcub/cooks_kitchen"
issueTrackerURL="https://github.com/moltenwolfcub/cooks_kitchen/issues"
updateJSONURL="https://raw.githubusercontent.com/moltenwolfcub/cooks_kitchen/master/update.json"
logoFile="cooks_kitchen.png"
authors="MoltenWolfCub"
description='''
A Minecraft Food Mod
'''


[[dependencies.cooks_kitchen]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cooks_kitchen]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
