modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"
issueTrackerURL="https://github.com/moltenwolfcub/crafted_cuisine/issues"
showAsResourcePack=false

[[mods]]
modId="crafted_cuisine"
version="1.18.2-0.0.1"
displayName="Crafted Cuisine"
displayURL="https://github.com/moltenwolfcub/crafted_cuisine"
issueTrackerURL="https://github.com/moltenwolfcub/crafted_cuisine/issues"
updateJSONURL="https://raw.githubusercontent.com/moltenwolfcub/crafted_cuisine/master/update.json"
logoFile="crafted_cuisine.png"
authors="MoltenWolfCub"
description='''
A Minecraft Food Mod
'''


[[dependencies.crafted_cuisine]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.crafted_cuisine]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.crafted_cuisine]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.0.27,)"
    ordering="NONE"
    side="BOTH"
