modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"
issueTrackerURL="https://github.com/moltenwolfcub/create_food/issues"
showAsResourcePack=false

[[mods]]
modId="create_food"
version="1.18.2-0.0.1"
displayName="Create Food"
displayURL="https://github.com/moltenwolfcub/create_food"
logoFile="create_food.png"
authors="MoltenWolfCub & Simibubi(Author of Create)"
description='''
A create food addon
'''


[[dependencies.create_food]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_food]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

#[[dependencies.create_food]]
#    modId="create"
#    mandatory=true
#    versionRange="[0.4e,)"
